# Generated by Django 4.1.1 on 2022-11-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_codemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='title_tag',
            field=models.CharField(default='gege', max_length=255),
        ),
    ]
