# Generated by Django 4.1.1 on 2022-11-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_codemy', '0002_reg_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='title_tag',
            field=models.DateTimeField(),
        ),
    ]
