# Generated by Django 4.1.1 on 2022-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_codemy', '0003_alter_reg_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
