# Generated by Django 4.1.1 on 2022-11-23 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_codemy', '0004_alter_reg_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
